# Site settings
title: Hello, World!
header-img: img/home-bg.png
email: domingu4@gmail.com
copyright_name: ariellex3
description: > # this means to ignore newlines until "baseurl:"
  One Woman's Journey Through Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ariellex3
github_username:  ariellex3
learn_profile: ariellex3
email_username: domingu4@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
